Fix resolution of `wasm_bindgen` in `js!` macro
This fixes an issue that, when a dependent crate depends on `stdweb` for
the use of the `js!` macro but does not specify the dependency
`wasm_bindgen`, attempting to build for the target
`wasm32-unknown-unknown` (or using `wasm-pack` and friends) will yield
the following error:

    error[E0433]: failed to resolve: use of undeclared type or module
    `wasm_bindgen`